=== DW-TheWeasel/script.moviequiz/resources/strings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="strings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="string" type="stringType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="stringType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== DW-TheWeasel/script.moviequiz/resources/language/Spanish/strings.xml
<?xml version="1.0" encoding="utf-8"?>
<strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../strings.xsd">
    <!-- -->
    <string id="30000">Pregunta %d de %d</string>
    <string id="30001">Correcto:</string>
    <string id="30002">Incorrecto:</string>
    <string id="30003">Juego Terminado</string>
    <string id="30004">Su puntuación fue %d de %d</string><!-- 1st %d is score, 2nd %d is total question -->

    <string id="30005">Especiales</string><!-- same value as id="20381" in main xbmc strings.xml -->
    <string id="30006">Temporada %i</string><!-- same value as id="20358" in main xbmc strings.xml -->
    <string id="30007">%B %e, %Y</string><!-- episode first aired date format: http://docs.python.org/library/time.html#time.strftime -->
    <string id="30008">[B]Cargando[/B]</string>

    <!-- Menu -->
    <string id="30100">Jugar Movie Quiz</string>
    <string id="30101">Jugar TV Quiz</string>
    <string id="30102">Configuración</string>
    <string id="30103">Salir</string>

    <string id="30110">[B]Trivia de la colección de Películas[/B]</string>
    <string id="30111">%d películas</string><!-- %d is movie count -->
    <string id="30112">%d actores</string><!-- %d is actor count -->
    <string id="30113">%d directores</string><!-- %d is director count -->
    <string id="30114">%d estudios</string><!-- %d is studio count -->
    <string id="30115">%d horas de entretenimiento</string>

    <string id="30120">[B]Trivia de la colección de Shows de TV[/B]</string>
    <string id="30121">%d Shows de TV</string><!-- %d is TV show count -->
    <string id="30122">%d temporadas</string><!-- %d is season count -->
    <string id="30123">%d episodios</string><!-- %d is episodes count -->

    <!-- Movie Questions -->
    <string id="30400">¿Cuál película es esta?</string>
    <string id="30401">En cuál película no aparece %s?</string><!-- %s is actor name -->
    <string id="30402">¿En qué año se estrenó %s?</string><!-- %s is movie title -->
    <string id="30403">¿Cuál slogan le corresponde a %s?</string><!-- %s is movie title -->
    <string id="30404">¿Quién dirigió %s?</string><!-- %s is movie title -->
    <string id="30405">¿Cuál estudio publicó %s?</string><!-- %s is movie title -->
    <string id="30406">¿Quién es este actor/actriz?</string>
    <string id="30407">¿Quién interpreta a %s en %s?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30408">¿Quién provee la voz para %s en %s?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30409">¿De cuál película es esta cita?</string>
    <string id="30410">¿Cuál película es la más reciente?</string>
    <string id="30411">¿Cuál película no fue dirigida por %s?</string><!-- %s is director name -->
    <string id="30412">¿Cuál actor/actriz aparece en todas estas películas?</string>
    <string id="30413">¿Cuál actor/actriz aparece en %s además de %s?</string><!-- 1st %s is movie title, 2nd %s is actor name -->
    <string id="30414">¿Cuál película tiene la mayor duración?</string>

    <!-- TV show Questions -->
    <string id="30450">¿Cuál es este show de TV?</string>
    <string id="30451">¿Cuál temporada de %s es esta?</string><!-- %s is tvshow title -->
    <string id="30452">¿Cuál episodio de %s es este?</string><!-- %s is tvshow title -->
    <string id="30453">¿Cuándo salió al aire por primera vez el episodio %s del show %s?</string><!-- 1st %s is episode, 2nd %s is tvshow title -->
    <string id="30454">¿Cuándo salió al aire por primera vez %s?</string><!-- %s is tvshow title -->
    <string id="30455">¿Quién interpreta a %s en %s?</string><!-- 1st %s is role, 2nd %s is tvshow title -->
    <string id="30456">¿Quién provee la voz para %s en %s?</string><!-- 1st %s is role, 2nd %s is tvshow title -->


    <!-- Settings strings -->
    <string id="30500">General</string>
    <string id="30501">Películas</string>
    <string id="30502">Shows de TV</string>
    <string id="30503">Descargas</string>

    <string id="30510">Limitar cantidad de preguntas</string>
    <string id="30511">Límite de Preguntas</string>
    <string id="30512">Limitar selección de películas en base a calificación MPAA</string>
	<string id="30513">Calificación MPAA máxima</string>
    <string id="30514">Mostrar la respuesta correcta cuando conteste incorrectamente</string>
    <string id="30515">Sólo utilizar películas ya vistas en las preguntas</string>
    <string id="30516">Limitar la selección de los shows de TV basado en la calificación del Contenido</string>
	<string id="30517">Calificación de Contenido máxima</string>
    <string id="30519">Descargar datos de IMDB...</string>
    <string id="30520">Descargando datos de IMDB...</string>
    <string id="30521">Recuperados %d de %d mb.</string>
    <string id="30522">Algunas preguntas requieren de datos locales adicionales,</string>
    <string id="30523">los cuales pueden ser descargados abajo:</string>

    <string id="39999">Traducido por bsoriano</string>
</strings>

=== DW-TheWeasel/script.moviequiz/resources/language/French/strings.xml
<?xml version="1.0" encoding="utf-8"?>
<strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../strings.xsd">
    <!-- -->
    <string id="30000">Question %d sur %d</string>
    <string id="30001">Score :</string>
    <string id="30002">Question value:</string>
    <string id="30003">Fin du Quiz</string>
    <string id="30004">Votre score %d sur %d</string><!-- 1st %d is score, 2nd %d is total question -->

    <string id="30005">Specials</string><!-- same value as id="20381" in main xbmc strings.xml -->
    <string id="30006">Saison %i</string><!-- same value as id="20358" in main xbmc strings.xml -->
    <string id="30007">%d %B %Y</string><!-- episode first aired date format: http://docs.python.org/library/time.html#time.strftime -->

    <string id="30008">[B]Chargement en cours[/B]</string>

    <!-- Menu -->
    <string id="30100">Quiz de Films</string>
    <string id="30101">Quiz de Séries TV</string>
    <string id="30102">Paramètres</string>
    <string id="30103">Quitter</string>

    <string id="30110">[B]Collection de films[/B]</string>
    <string id="30111">%d films</string><!-- %d is movie count -->
    <string id="30112">%d acteurs</string><!-- %d is actor count -->
    <string id="30113">%d réalisateurs</string><!-- %d is director count -->
    <string id="30114">%d studios</string><!-- %d is studio count -->
    <string id="30115">%d heures de divertissement</string>

    <string id="30120">[B]Collection de Séries TV[/B]</string>
    <string id="30121">%d Séries TV</string><!-- %d is TV show count -->
    <string id="30122">%d saisons</string><!-- %d is season count -->
    <string id="30123">%d épisodes</string><!-- %d is episodes count -->

    <!-- Movie Questions -->
    <string id="30400">Quel est ce film ?</string>
    <string id="30401">Dans quel film [B]%s[/B] ne joue pas ?</string><!-- %s is actor name -->
    <string id="30402">En quelle année [B]%s[/B] est sortie ?</string><!-- %s is movie title -->
    <string id="30403">Quel est le slogan du film [B]%s[/B] ?</string><!-- %s is movie title -->
    <string id="30404">Qui a réalisé [B]%s[/B] ?</string><!-- %s is movie title -->
    <string id="30405">Quel studio a produit [B]%s[/B] ?</string><!-- %s is movie title -->
    <string id="30406">Quel est cet acteur ?</string>
    <string id="30407">Qui joue le personnage de [B]%s[/B] dans [B]%s[/B] ?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30408">Qui fait la voix de [B]%s[/B] dans [B]%s[/B] ?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30409">De quel film provient cet extrait ?</string>
    <string id="30410">Quel film est le plus récent ?</string>
    <string id="30411">Quel film n'est pas réalisé par [B]%s[/B] ?</string><!-- %s is director name -->
    <string id="30412">Quel acteur joue dans ces films ?</string>
    <string id="30413">Quel acteur joue dans [B]%s[/B] aux côtés de [B]%s[/B] ?</string><!-- 1st %s is movie title, 2nd %s is actor name -->
    <string id="30414">Quel film est le plus long ?</string>

    <!-- TV show Questions -->
    <string id="30450">Quelle est cette Série TV ?</string>
    <string id="30451">Quelle est cette saison de [B]%s[/B] ?</string><!-- %s is tvshow title -->
    <string id="30452">Quel est cet épisode de [B]%s[/B] ?</string><!-- %s is tvshow title -->
    <string id="30453">Quand l'épisode [B]%s[/B] de [B]%s[/B] a été diffusée pour la première fois ?</string><!-- 1st %s is episode, 2nd %s is tvshow title -->
    <string id="30454">Quand la Série TV [B]%s[/B] a été diffusée pour la première fois ?</string><!-- %s is tvshow title -->
    <string id="30455">Qui joue le rôle de [B]%s[/B] dans [B]%s[/B] ?</string><!-- 1st %s is role, 2nd %s is tvshow title -->
    <string id="30456">Qui fait la voix de [B]%s[/B] dans [B]%s[/B] ?</string><!-- 1st %s is role, 2nd %s is tvshow title -->

    <!-- Settings strings -->
    <string id="30500">Général</string>
    <string id="30501">Films</string>
    <string id="30502">Séries TV</string>
    <string id="30503">Téléchargements</string>
    <string id="30504">Meilleurs scores</string>
    <string id="30505">Questions</string>

    <string id="30510">Limiter le nombre de questions</string>
    <string id="30511">Limite de Questions</string>
    <string id="30512">Limiter la sélection des films par rapport au contrôle parental</string>
	<string id="30513">Max. MPAA rating</string>
    <string id="30514">Affiche la bonne réponse quand la votre est incorrecte</string>
    <string id="30515">Prendre seulement les films déjà vus pour le Quiz</string>
    <string id="30516">Limiter la sélection des série TV par rapport au contrôle parental</string>
	<string id="30517">Max. Content rating</string>
    <string id="30519">Télécharger sur IMDB...</string>
    <string id="30520">Téléchargement des données d'IMDB...</string>
    <string id="30521">%d sur %d Mo.</string>
    <string id="30522">Certaines questions requièrent plus d'informations,</string>
    <string id="30523">vous pouvez les télécharger ci-dessous :</string>
    <string id="30524">Pseudo</string>

    <!-- Game type strings -->
    <string id="30600">[B]Choisissez un Quiz de Films[/B]</string>
    <string id="30601">[B]Choisissez un Quiz de Séries TV[/B]</string>
    <string id="30602">Illimité</string>
    <string id="30603">Limite de Temps</string>
    <string id="30604">Limite de Questions</string>
    <string id="30605">Annuler</string>
    <string id="30606">Jouer</string>

    <string id="30610">Pas de limite de temps</string>
    <string id="30611">Pas de limite de questions</string>
    <string id="30612">Arréter le Quiz en utilisant Quitter</string>
    <string id="30613">Le Quiz s'arrête après</string>

    <!-- Game over strings -->
    <string id="30700">[B]Fin du Quiz[/B]</string>
    <string id="30701">Recommencer</string>
    <string id="30702">Meilleurs Scores</string>
    <string id="30703">Meilleurs Scores locaux</string>
    <string id="30704">Menu général</string>



    <string id="39999">Traduit par DanoneKiD</string>
</strings>

=== DW-TheWeasel/script.moviequiz/resources/language/Bulgarian/strings.xml
<?xml version="1.0" encoding="utf-8"?>
<strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../strings.xsd">
    <!-- -->
    <string id="30000">Въпрос %d от %d</string>
    <string id="30001">Правилни:</string>
    <string id="30002">Грешни:</string>
    <string id="30003">Играта приключи</string>
    <string id="30004">Вие отблязахте %d от %d</string><!-- 1st %d is score, 2nd %d is total question -->

    <string id="30005">Спешъли</string><!-- same value as id="20381" in main xbmc strings.xml -->
    <string id="30006">Сезон %i</string><!-- same value as id="20358" in main xbmc strings.xml -->
    <string id="30007">%B %e, %Y</string><!-- episode first aired date format: http://docs.python.org/library/time.html#time.strftime -->
    <string id="30008">[B]Зарежда...[/B]</string>

    <!-- Menu -->
    <string id="30100">Игра с Филми</string>
    <string id="30101">Игра със Сериали</string>
    <string id="30102">Настройки</string>
    <string id="30103">Изход</string>

     <string id="30110">[B]Любопитни факти от филми[/B]</string>
    <string id="30111">%d филма</string><!-- %d is movie count -->
    <string id="30112">%d актьора</string><!-- %d is actor count -->
    <string id="30113">%d режисьора</string><!-- %d is director count -->
    <string id="30114">%d студиа</string><!-- %d is studio count -->
    <string id="30115">%d часа забавления</string>

    <string id="30120">[B]Любопитни факти от сериали[/B]</string>
    <string id="30121">%d TV сериали</string><!-- %d is TV show count -->
    <string id="30122">%d сезона</string><!-- %d is season count -->
    <string id="30123">%d епизода</string><!-- %d is episodes count -->

    <!-- Movie Questions -->
    <string id="30400">Кой филм е това?</string>
    <string id="30401">В кой филм [B]%s[/B] не участва?</string><!-- %s is actor name -->
    <string id="30402">Коя година [B]%s[/B] е издаден?</string><!-- %s is movie title -->
    <string id="30403">Кой лозунг принадлежи на [B]%s[/B]?</string><!-- %s is movie title -->
    <string id="30404">Кой режисира [B]%s[/B]?</string><!-- %s is movie title -->
    <string id="30405">Кое студио издава [B]%s[/B]?</string><!-- %s is movie title -->
    <string id="30406">Кой актьор е това?</string>
    <string id="30407">Кой играе [B]%s[/B] в [B]%s[/B]?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30408">Кой озвучава [B]%s[/B] в [B]%s[/B]?</string><!-- 1st %s is role, 2nd %s is movie title -->
    <string id="30409">От кой филм е цитатът?</string>
    <string id="30410">Кой е най-новият филм?</string>
    <string id="30411">Кой филм не е режисиран от [B]%s[/B]?</string><!-- %s is director name -->
    <string id="30412">Кой актьор участва в тези филми?</string>
    <string id="30413">Кой актьор участва в [B]%s[/B] освен [B]%s[/B]?</string><!-- 1st %s is movie title, 2nd %s is actor name -->
    <string id="30414">Кой е най-дългият филм?</string>

    <!-- TV show Questions -->
    <string id="30450">Кой TV сериал е това?</string>
    <string id="30451">Кой сезон на [B]%s[/B] е това?</string><!-- %s is tvshow title -->
    <string id="30452">Кой епизод на [B]%s[/B] е това?</string><!-- %s is tvshow title -->
    <string id="30453">Кога е [B]%s[/B] на [B]%s[/B] излъчен за пръв път?</string><!-- 1st %s is episode, 2nd %s is tvshow title -->
    <string id="30454">Кога е [B]%s[/B] излъчен за пръв път?</string><!-- %s is tvshow title -->
    <string id="30455">Кой играе [B]%s[/B] в [B]%s[/B]?</string><!-- 1st %s is role, 2nd %s is tvshow title -->
    <string id="30456">Кой озвучава [B]%s[/B] в [B]%s[/B]?</string><!-- 1st %s is role, 2nd %s is tvshow title -->

    <!-- Settings strings -->
    <string id="30500">Общи</string>
    <string id="30501">Филми</string>
    <string id="30502">TV Сериали</string>
    <string id="30503">Изтегляния</string>

    <string id="30510">Ограничи броя на въпросите</string>
    <string id="30511">Ограничение на въпросите</string>
    <string id="30512">Ограничи избирането на филмите на база MPAA рейтинга</string>
    <string id="30513">Макс. MPAA рейтинг</string>
    <string id="30514">Показвай правилния отговор, когато се отговори неправилно</string>
    <string id="30515">Използвай само гледаните филми във въпросите</string>
    <string id="30516">Ограничи избора на TV сериали на база Content рейтинга</string>
    <string id="30517">Макс. Content рейтинг</string>
    <string id="30519">Изтегли данни от IMDB</string>
    <string id="30520">Изтеглям данни от IMDB...</string>
    <string id="30521">Получени %d от %d mb.</string>
    <string id="30522">Някои въпроси изискват допълнителни локални данни,</string>
    <string id="30523">които могат да бъдат свалени чрез:</string>

    <!-- Game type strings -->
    <string id="30600">[B]Избери Movie Quiz тип на играта[/B]</string>
    <string id="30601">[B]Избери TV Quiz тип на играта[/B]</string>
    <string id="30602">Неограничена</string>
    <string id="30603">Ограничена по време</string>
    <string id="30604">Ограничена по въпроси</string>
    <string id="30605">Отказ</string>
    <string id="30606">Играй</string>

    <string id="30610">Без лимит по време</string>
    <string id="30611">Без лимит по въпроси</string>
    <string id="30612">Край на играта, използвайки опцията 'Изход'</string>
    <string id="30613">Играта ще приключи след</string>


    <string id="39999">Превод: Пламен Петков</string>
</strings>
